/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsModal: typeof import('./src/components/maps/modals/alertsModal.vue')['default']
    AlertsPanel: typeof import('./src/components/global/panels/AlertsPanel.vue')['default']
    AreaChart: typeof import('./src/components/charts/AreaChart.vue')['default']
    AreaDetailsModal: typeof import('./src/components/maps/modals/areaDetailsModal.vue')['default']
    BarChart: typeof import('./src/components/eChart/BarChart.vue')['default']
    ComplaintDetailsModal: typeof import('./src/components/maps/modals/complaintDetailsModal.vue')['default']
    ComplaintsModal: typeof import('./src/components/maps/modals/complaintsModal.vue')['default']
    ComplaintsPanel: typeof import('./src/components/global/panels/ComplaintsPanel.vue')['default']
    DailyReportsPanel: typeof import('./src/components/global/panels/DailyReportsPanel.vue')['default']
    DonutChart: typeof import('./src/components/charts/DonutChart.vue')['default']
    DualBarChart: typeof import('./src/components/charts/DualBarChart.vue')['default']
    FieldTeamsPanel: typeof import('./src/components/global/panels/FieldTeamsPanel.vue')['default']
    InteractiveMap: typeof import('./src/components/maps/InteractiveMap.vue')['default']
    InteractiveMapMapbox: typeof import('./src/components/maps/InteractiveMapMapbox.vue')['default']
    LineChart: typeof import('./src/components/eChart/LineChart.vue')['default']
    LocationsPanel: typeof import('./src/components/global/panels/LocationsPanel.vue')['default']
    MainAxesPanel: typeof import('./src/components/global/panels/MainAxesPanel.vue')['default']
    MapFooter: typeof import('./src/components/global/MapFooter.vue')['default']
    MapLoader: typeof import('./src/components/global/MapLoader.vue')['default']
    MapPanel: typeof import('./src/components/global/MapPanel.vue')['default']
    MapStatisticsPanel: typeof import('./src/components/global/MapStatisticsPanel.vue')['default']
    MapTopNavbar: typeof import('./src/components/global/MapTopNavbar.vue')['default']
    PieChart: typeof import('./src/components/eChart/PieChart.vue')['default']
    PreperationPanel: typeof import('./src/components/global/panels/PreperationPanel.vue')['default']
    ProfileModal: typeof import('./src/components/global/ProfileModal.vue')['default']
    RadialBarChart: typeof import('./src/components/charts/RadialBarChart.vue')['default']
    ReportDetailsModal: typeof import('./src/components/maps/modals/reportDetailsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsFilter: typeof import('./src/components/global/StatisticsFilter.vue')['default']
    SupervisorDetailsModal: typeof import('./src/components/maps/modals/supervisorDetailsModal.vue')['default']
    SupervisorsPanel: typeof import('./src/components/global/panels/SupervisorsPanel.vue')['default']
    TopNavbar: typeof import('./src/components/global/TopNavbar.vue')['default']
    UserDetailsModal: typeof import('./src/components/maps/modals/userDetailsModal.vue')['default']
  }
}
