/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/global/panels/MainAxesPanel copy 2.vue')['default']
    3: typeof import('./src/components/global/panels/MainAxesPanel copy 3.vue')['default']
    4: typeof import('./src/components/global/panels/MainAxesPanel copy 4.vue')['default']
    5: typeof import('./src/components/global/panels/MainAxesPanel copy 5.vue')['default']
    6: typeof import('./src/components/global/panels/MainAxesPanel copy 6.vue')['default']
    AreaChart: typeof import('./src/components/charts/AreaChart.vue')['default']
    BarChart: typeof import('./src/components/eChart/BarChart.vue')['default']
    ComplaintsPanel: typeof import('./src/components/global/panels/ComplaintsPanel.vue')['default']
    copy: typeof import('./src/components/global/panels/MainAxesPanel copy.vue')['default']
    DailyReportsPanel: typeof import('./src/components/global/panels/DailyReportsPanel.vue')['default']
    DonutChart: typeof import('./src/components/charts/DonutChart.vue')['default']
    DualBarChart: typeof import('./src/components/charts/DualBarChart.vue')['default']
    FieldTeamsPanel: typeof import('./src/components/global/panels/FieldTeamsPanel.vue')['default']
    InteractiveMap: typeof import('./src/components/maps/InteractiveMap.vue')['default']
    InteractiveMapMapbox: typeof import('./src/components/maps/InteractiveMapMapbox.vue')['default']
    LineChart: typeof import('./src/components/eChart/LineChart.vue')['default']
    LocationsPanel: typeof import('./src/components/global/panels/LocationsPanel.vue')['default']
    MainAxesPanel: typeof import('./src/components/global/panels/MainAxesPanel.vue')['default']
    MapCompanyDetailsDialog: typeof import('./src/components/maps/dialogs/MapCompanyDetailsDialog.vue')['default']
    MapEntityDetailsDialog: typeof import('./src/components/maps/dialogs/MapEntityDetailsDialog.vue')['default']
    MapFooter: typeof import('./src/components/global/MapFooter.vue')['default']
    MapLoader: typeof import('./src/components/global/MapLoader.vue')['default']
    MapObserverDetailsDialog: typeof import('./src/components/maps/dialogs/MapObserverDetailsDialog.vue')['default']
    MapOperatorDetailsDialog: typeof import('./src/components/maps/dialogs/MapOperatorDetailsDialog.vue')['default']
    MapPanel: typeof import('./src/components/global/MapPanel.vue')['default']
    MapStatisticsPanel: typeof import('./src/components/global/MapStatisticsPanel.vue')['default']
    MapTaskDetailsDialog: typeof import('./src/components/maps/dialogs/MapTaskDetailsDialog.vue')['default']
    MapTicketTypesDialog: typeof import('./src/components/maps/dialogs/MapTicketTypesDialog.vue')['default']
    MapTopNavbar: typeof import('./src/components/global/MapTopNavbar.vue')['default']
    PieChart: typeof import('./src/components/eChart/PieChart.vue')['default']
    PreperationPanel: typeof import('./src/components/global/panels/PreperationPanel.vue')['default']
    ProfileModal: typeof import('./src/components/global/ProfileModal.vue')['default']
    RadialBarChart: typeof import('./src/components/charts/RadialBarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsFilter: typeof import('./src/components/global/StatisticsFilter.vue')['default']
    SupervisorsPanel: typeof import('./src/components/global/panels/SupervisorsPanel.vue')['default']
    TopNavbar: typeof import('./src/components/global/TopNavbar.vue')['default']
  }
}
